config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'

  get "/prepregnancy" => "pages#goods"
  get "/goods" => "pages#goods"

  get "/plans" => "pages#pricing", as: "pricing"
  get "/almost-ready" => "pages#waiting_list", as: "almost_ready"
  root 'pages#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  has_and_belongs_to_many :personas
end

app/models/persona.rb
class Persona < ActiveRecord::Base
  has_and_belongs_to_many :recommended_items, class_name: 'Item'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # pass view context to all serializers
  serialization_scope :view_context
end

app/controllers/hello_world_controller.rb
class HelloWorldController < ApplicationController
  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index

  end

  def goods
    @personas = ActiveModel::ArraySerializer.new(Persona.all.order(created_at: :asc), scope: self.view_context)
    @inventory = ActiveModel::ArraySerializer.new(Item.all, scope: self.view_context)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hello_world/index.html.erb
<h1 class="alert alert-info this-works">Server Rendering</h1>
<%= react_component("HelloWorldApp",props:
                     @hello_world_props,
                     prerender: false) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SnackDojo</title>
  <link href="https://unpkg.com/basscss@7.1.1/css/basscss.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Facebook Pixel Code -->
  <script>
  !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
  n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
  document,'script','//connect.facebook.net/en_US/fbevents.js');

  fbq('init', '747142328764035');
  fbq('track', "PageView");</script>
  <noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=747142328764035&ev=PageView&noscript=1"
  /></noscript>
  <!-- End Facebook Pixel Code -->
</head>
<body>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-47263513-1', 'auto');
    ga('send', 'pageview');

  </script>

  <!-- start Mixpanel --><script type="text/javascript">(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
  for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f)}})(document,window.mixpanel||[]);
  mixpanel.init("7873e4c11f5fcfde142e58b5293a9d76");</script><!-- end Mixpanel -->


<%= yield %>

</body>
</html>

app/views/pages/_footer.html.erb
<div class="py2 border-top">
  <div class="sm-col-6 mx-auto muted center">
    2015 SnackDojo. Made with <span class="red">&hearts;</span> in Santa Monica, CA.
  </div>
</div>

app/views/pages/_partnerbrands.html.erb
<div class="m3">
  <div class="container">
    <div class="h1 bold center p2">
      Partner brands
    </div>
    <div class="sm-col-10 mx-auto">
      <div class="flex flex-wrap flex-justify">
        <% Dir.glob("#{Rails.root.join('app', 'assets', 'images', 'logos')}/*.{jpg,png}").map{|f| f.split('/').last}.shuffle.each do |logo| %>
          <div class="m1" style="height:100px;width:100px;background: url('<%= asset_url("logos/#{logo}") %>') no-repeat center/contain">
          </div>
        <% end %>
      </div>
      <!-- <div class="center gray">
        Have a brand you'd like to see? Click here to request it!
      </div> -->
    </div>
  </div>
</div>

app/views/pages/goods.html.erb
<div>
  <div class="container">
    <div class="mt2 p1 px3" style="width:10rem;">
      <%= image_tag asset_url('logo.svg') %>
    </div>
    <%= react_component("SnackDojoApp", props:
      {
        personas: @personas,
        inventory: @inventory,
      },
      prerender: true) %>
  </div>
  <script type="text/javascript">
    $(document).ready(function() {
      fbq('trackCustom', 'ViewedInventoryPage');
    })
  </script>

  <%= render 'footer' %>
</div>

app/views/pages/index.html.erb
<div class="flex flex-column" style="min-height:100vh;">
  <div class="flex-auto" style="background: url(<%= asset_url 'stock/sliced-banana-orange-small.jpg' %>) no-repeat center/cover">
    <div class="container">
      <div class="p3 mt3" style="background-color:rgba(255, 255, 255, 0.75);">
        <p class="h1 center">Healthy snacks for clever moms</p>
        <p class="h2">
          From pre-pregnancy to postpartum recovery, get what you need to be healthy, energized and happy, straight to your door.
        </p>
        <div class="center">
          <h3>Get started by selecting your current stage</h3>
          <div class="flex flex-wrap flex-justify mb3">
            <div class="p1 center border border-black flex-auto">
              <div>
                Planning for a baby
              </div>
              <img src="http://placehold.it/150x150" />
            </div>
            <div class="p1 center border border-black flex-auto">
              <div>
                1st trimester
              </div>
              <img src="http://placehold.it/150x150" />
            </div>
            <div class="p1 center border border-black flex-auto">
              <div>
                2nd trimester
              </div>
              <img src="http://placehold.it/150x150" />
            </div>
            <div class="p1 center border border-black flex-auto">
              <div>
                3rd trimester
              </div>
              <img src="http://placehold.it/150x150" />
            </div>
            <div class="p1 center border border-black flex-auto">
              <div>
                Postpartum
              </div>
              <img src="http://placehold.it/150x150" />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
  $(document).ready(function() {
    mixpanel.track("page-view", {
      'name': 'home page',
      'url': window.location.pathname
    });
    fbq('trackCustom', 'ViewedHomepage');
    // TODO: add mixpanel tracking to stage selection

  })
  </script>
  <%= render 'partnerbrands' %>
  <%= render 'footer' %>
</div>

app/views/pages/pricing.html.erb
<div class="flex flex-column" style="min-height:100vh;">
  <div class="flex-auto" style="background: url(<%= asset_url 'stock/sliced-banana-orange-small.jpg' %>) no-repeat center/cover">
    <div class="container">
      <div class="p3 mt3 sm-col-8 mx-auto" style="background-color:rgba(255, 255, 255, 0.8);">
        <p class="h1 center">Plans and pricing</p>
        <p>
          Each box contains a week's supply of cold pressed juices, healthy snacks, and special discounts from our partners. All plans have one trimester minimums.
        </p>
        <p class="h3 bold">
          Select a plan to get started
        </p>
        <ul class="h3 list-reset">
          <li class="m1 p2 border border-black pointer plan" id="basic">
            <strong>Basic</strong> - 2 boxes a month, $35 per box
          </li>
          <li class="m1 p2 border border-black pointer plan" id="value">
            <strong>Value</strong> - 3 boxes a month, $30 per box
          </li>
          <li class="m1 p2 border border-black pointer plan" id="power">
            <strong>Power</strong> - 4 boxes a month, $30 per box
          </li>
        </ul>
        <div class="center border-top py2">
          <p>
            Not ready for a plan yet? Subscribe to our mailing list to receive special discounts from our partners.
          </p>
          <a href="http://eepurl.com/bJyH-1">
            <div class="btn btn-primary center" id="mailing-list">
              Subscribe
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
  <script>

  $(document).ready(function() {
    mixpanel.track("page-view", {
      'name': 'plans and pricing',
      'url': window.location.pathname
    });
    fbq('track', 'ViewedPricingPage');
    $('li.plan').click(function(e) {
      mixpanel.track('plan clicked', {
        'level': e.target.id
      })
      e.preventDefault()
      window.location = "<%= almost_ready_url %>"
    })
    $('#mailing-list').click(function() {
      mixpanel.track('subscribe to mailing list clicked')
    })
  })

  </script>
  <%= render 'partnerbrands' %>
  <%= render 'footer' %>
</div>

app/views/pages/scratchpad.html.erb
<div class="container">
  <div class="sm-col-7 mx-auto p2">
    <div class="h1 bold center">
      Sample box (first trimester)
    </div>
    <div class="p2 flex flex-justify flex-wrap">
      <div>
        <ul class="list-reset">
          <li>
            Yogurt drink
          </li>
          <li>
            Dried apricots (Eden)
          </li>
          <li>
            Fruit and cheese scones
          </li>
          <li>
            Carrot sticks and hummus dip
          </li>
          <li>
            Mixed nuts and dried fruit
          </li>
          <li>
            Banana bread
          </li>
        </ul>
      </div>
      <div>
        <ul class="list-reset">
          <li>
            Greek yogurt
          </li>
          <li>
            Green tea
          </li>
          <li>
            Herbal tea
          </li>
          <li>
            Cold pressed kale, spinach, celery juice
          </li>
          <li>
            Cold pressed kale, cumcumber, apple juice
          </li>
          <li>
            Cold pressed carrot and orange juice
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
First trimester - folate-rich foods for healthy brain and spinal cord development, and vitamin B6 to help with morning sickness.
Second trimester - foods with omega 3 fatty acids for brain devlopment, calcium and vitamin D for bones and teeth, and iron-rich foods for red blood cells.
Third trimester - energy boosting foods, foods with vitamin K to help with blood clotting, and extra snacks to meet your extra calorie requirements for third trimester.

<div className="flex flex-center">
  <img src="http://placehold.it/50x50" className="p1 flex-none" />
  <div>Complex carbs (sustained energy throughout the day, low glycemic index)</div>
</div>
<div className="flex flex-center">
  <img src="http://placehold.it/50x50" className="p1 flex-none" />
  <div>Plant proteins (sustained energy throughout the day, low glycemic index)</div>
</div>
<div className="flex flex-center">
  <img src="http://placehold.it/50x50" className="p1 flex-none" />
  <div>Omega-3 fatty acids (reduce risk of preterm birth and preeclampsia)</div>
</div>

app/views/pages/waiting_list.html.erb
<div class="flex flex-column" style="min-height:100vh;">
  <div class="flex-auto" style="background: url(<%= asset_url 'stock/sliced-banana-orange-small.jpg' %>) no-repeat center/cover">
    <div class="container">
      <div class="p3 mt3 sm-col-8 mx-auto" style="background-color:rgba(255, 255, 255, 0.8);">
        <p class="h3 bold center">
          Hello! You caught us before we are ready.
        </p>
        <div class="py2 center">
          <p>
            We're working hard to put the finishing touches on SnackDojo. It should be ready for you soon!
          </p>
          <p>
            In the meantime, if you'd like to receive a reminder when we're ready, enter your email in our subscribe form.
          </p>
          <a href="http://eepurl.com/bJyH-1">
            <div class="btn btn-primary center" id="mailing-list">
              Click to Subscribe
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
  <script>
  $(document).ready(function() {
    mixpanel.track("page-view", {
      'name': 'waiting_list',
      'url': window.location.pathname
    });
    fbq('track', 'ViewedNotReadyPage');
  })
  </script>
  <%= render 'partnerbrands' %>
  <%= render 'footer' %>
</div>